/* Lists saved reports with search filters, status, downloads, and page navigation. */
import {
  Box,
  Button,
  Chip,
  CircularProgress,
  MenuItem,
  Paper,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  TextField,
  Typography,
} from "@mui/material";
import { Refresh, History } from "@mui/icons-material";
import { types } from "./reportConstants";
import { dateTime } from "./reportUtils";
import { context } from "./reportUtils";
import ReportStatusChip from "./ReportStatusChip";
import type { ReportsState } from "./useReports";

type Props = Pick<
  ReportsState,
  | "busy"
  | "tableBusy"
  | "history"
  | "historyPage"
  | "setHistoryPage"
  | "historyType"
  | "setHistoryType"
  | "historyStatus"
  | "setHistoryStatus"
  | "historySearch"
  | "setHistorySearch"
  | "scheduleFilter"
  | "setScheduleFilter"
  | "setRefresh"
  | "download"
  | "view"
>;

export default function ReportHistory({
  busy,
  tableBusy,
  history,
  historyPage,
  setHistoryPage,
  historyType,
  setHistoryType,
  historyStatus,
  setHistoryStatus,
  historySearch,
  setHistorySearch,
  scheduleFilter,
  setScheduleFilter,
  setRefresh,
  download,
  view,
}: Props) {
  return (
    <Paper variant="outlined" className="report-panel">
      <Stack direction="row" sx={{ justifyContent: "space-between" }}>
        <Box>
          <Typography variant="h6">Report History</Typography>
          <Typography color="text.secondary">
            View saved reports and schedule execution results.
          </Typography>
        </Box>
        <Button
          startIcon={<Refresh />}
          onClick={() => setRefresh((v) => v + 1)}
        >
          Refresh
        </Button>
      </Stack>
      <div className="report-history-filters">
        <TextField
          select
          size="small"
          label="Report type"
          value={historyType}
          onChange={(e) => {
            setHistoryType(e.target.value);
            setHistoryPage(0);
          }}
        >
          <MenuItem value="">All reports</MenuItem>
          {types.map((t) => (
            <MenuItem key={t.id} value={t.id}>
              {t.name}
            </MenuItem>
          ))}
        </TextField>
        <TextField
          size="small"
          select
          label="Status"
          value={historyStatus}
          onChange={(e) => {
            setHistoryStatus(e.target.value);
            setHistoryPage(0);
          }}
        >
          <MenuItem value="">All statuses</MenuItem>
          {["COMPLETED", "FAILED", "GENERATING"].map((s) => (
            <MenuItem key={s} value={s}>
              {s}
            </MenuItem>
          ))}
        </TextField>
        <TextField
          size="small"
          label="Search reports"
          value={historySearch}
          onChange={(e) => {
            setHistorySearch(e.target.value);
            setHistoryPage(0);
          }}
        />
        {scheduleFilter && (
          <Chip
            label="Selected schedule"
            onDelete={() => {
              setScheduleFilter("");
              setHistoryPage(0);
            }}
          />
        )}
      </div>
      {tableBusy ? (
        <CircularProgress />
      ) : (
        <TableContainer>
          <Table size="small">
            <TableHead>
              <TableRow>
                {[
                  "Report",
                  "Generated by",
                  "Date / Time",
                  "Applied filters",
                  "Format",
                  "Status / Delivery",
                  "Actions",
                ].map((c) => (
                  <TableCell key={c}>{c}</TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {history.items.map((r) => (
                <TableRow key={r.id}>
                  <TableCell>{r.name}</TableCell>
                  <TableCell>{r.generated_by}</TableCell>
                  <TableCell>{dateTime(r.created_at)}</TableCell>
                  <TableCell sx={{ maxWidth: 300 }}>{context(r)}</TableCell>
                  <TableCell>{r.format}</TableCell>
                  <TableCell>
                    {<ReportStatusChip status={r.status} />}{" "}
                    {r.delivery_status && (
                      <ReportStatusChip status={r.delivery_status} />
                    )}
                    {r.error && (
                      <Typography
                        variant="caption"
                        color="error"
                        sx={{ display: "block" }}
                      >
                        {r.error}
                      </Typography>
                    )}
                  </TableCell>
                  <TableCell>
                    <Button onClick={() => view(r)}>View</Button>
                    <Button
                      disabled={busy || r.status !== "COMPLETED"}
                      onClick={() => download(r, r.format)}
                    >
                      Download
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      )}
      {!tableBusy && !history.total && (
        <div className="report-empty">
          <History />
          <Typography>No reports found</Typography>
        </div>
      )}
      <TablePagination
        component="div"
        count={history.total}
        page={historyPage}
        rowsPerPage={10}
        rowsPerPageOptions={[10]}
        onPageChange={(_, v) => setHistoryPage(v)}
      />
    </Paper>
  );
}
