from enum import StrEnum


DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 72

ACCESS_TOKEN_TYPE = "access"
REFRESH_TOKEN_TYPE = "refresh"
PASSWORD_RESET_TOKEN_TYPE = "password_reset"

BEARER_TOKEN_PREFIX = "Bearer"


class UserRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    COMPANY_ADMIN = "COMPANY_ADMIN"
    ANALYST = "ANALYST"
    VIEWER = "VIEWER"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class AuditAction(StrEnum):
    COMPANY_REGISTERED = "COMPANY_REGISTERED"
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_UPDATED = "CATEGORY_UPDATED"
    CATEGORY_DELETED = "CATEGORY_DELETED"
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"
    PRODUCT_ACTIVATED = "PRODUCT_ACTIVATED"
    PRODUCT_DEACTIVATED = "PRODUCT_DEACTIVATED"
    SALE_CREATED = "SALE_CREATED"
    SALE_UPDATED = "SALE_UPDATED"
    SALE_DELETED = "SALE_DELETED"
    INVENTORY_UPDATED = "INVENTORY_UPDATED"
    PRODUCT_OUT_OF_STOCK = "PRODUCT_OUT_OF_STOCK"


COMPANY_MANAGEMENT_ROLES = {
    UserRole.SUPER_ADMIN,
    UserRole.COMPANY_ADMIN,
}

ALL_AUTHENTICATED_ROLES = {
    UserRole.SUPER_ADMIN,
    UserRole.COMPANY_ADMIN,
    UserRole.ANALYST,
    UserRole.VIEWER,
}
